name: CD (on pr/main)
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest
    env:
      NEW_INFECTED_URL: ${{ secrets.NEW_INFECTED_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Lint
        run: npm run lint   
  # test:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Test
  #       run: npm run test
